spring.application.name=BootMVCProj01-FirstApp


#View Resolver cfgs
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#Embedded server port
server.port=4041

#Context Path 
server.servlet.context-path=/FirstApp


